#!/usr/bin/bash

gateway_ip=$(ip route show default |  awk '{print $3}')
gateway_interface=$(ip route show default | awk '{print $5}')
gateway_interface_ip=$(ifconfig "$gateway_interface" | grep 'inet ' | awk '{print $2}')


ip route replace default via 192.168.200.2 dev $(route -n | grep 192.168.200.0 | awk '{print $8}')
ip addr del $(gateway_interface_ip) dev $(gateway_interface)
echo "DNS=8.8.8.8 8.8.4.4" >> /etc/systemd/resolved.conf
systemctl restart systemd-resolved

while true
do

        ping -c3 -q 8.8.8.8
        if [ "$?" -eq 1 ]; then
                ip addr add $gateway_interface_ip dev $gateway_interface
                ip route replace default via $gateway_ip dev $gateway_interface
		echo "firewall has failed. Restoring network"
                
        fi

	sleep 30
done


