#!/usr/bin/bash

#gateway_ip=$(ip route show default | awk '{print $3}')
#gateway_interface=$(ip route show default | awk '{print $5}')
#gateway_interface_ip=$(ifconfig "$gateway_interface" | grep 'inet ' | awk '{print $2}')

#echo "Gateway IP: $gateway_ip"
#echo "Gateway Interface: $gateway_interface"
#echo "Gateway Interface IP: $gateway_interface_ip"

ip route replace default via 192.168.200.2 dev $(route -n | grep 192.168.200.0 | awk '{print $8}')
#ip addr del "$gateway_interface_ip" dev "$gateway_interface"
ip addr del 10.0.48.56/24 dev ens18


# Update DNS and restart systemd-resolved
echo "DNS=8.8.8.8 8.8.4.4" >> /etc/systemd/resolved.conf
systemctl restart systemd-resolved

while true
do
    ping -c3 -q 8.8.8.8
    if [ "$?" -eq 1 ]; then
        #ip addr add "$gateway_interface_ip" dev "$gateway_interface"
        #ip route replace default via "$gateway_ip" dev "$gateway_interface"
	ip addr add 10.0.48.56/24 dev ens18
	ip route replace default via 10.0.48.1 dev ens18
	ip route del default via 192.168.200.2 dev $(route -n | grep 192.168.200.0 | awk '{print $8}')
        echo "Firewall has failed. Restoring network"
    fi

    ping -I $(route -n | grep 192.168.200.0 | awk '{print $8}') -c3 8.8.8.8
    if [ "$?" -eq 1 ]; then
	ip route replace default via 192.168.200.2 dev $(route -n | grep 192.168.200.0 | awk '{print $8}')
	ip addr del 10.0.48.56/24 dev ens18
    fi 

    # Wait 30 seconds before retrying
    sleep 30
done

