FROM docker.io/library/postgres
run apt update -y && apt install vim openvpn net-tools procps tcpdump inetutils-ping  iproute2 inetutils-ping -y
#run route add -host 192.168.13.13 dev eth1
volume /mykeys
volume /var/lib/postgresql/data
workdir /mykeys
copy psql-server.sh /
#entrypoint openvpn --config client3.conf
#entrypoint tail -f /dev/null
entrypoint sh /psql-server.sh

